### ISSUE TITLE
右键没有“查找可用的PDF“

### ISSUE THREAD

**Issue by zhangwanshuai** [syt2/zotero-scipdf#17]
右键没有”查找可用的PDF“
zotero：7.0.1 (64-bit)
插件：1.1.1

禁用style插件后没有效果，移除其他插件后也没有效果

![image](https://github.com/user-attachments/assets/2e8746a4-3e46-4d97-99cc-4a4e3f99672c)
![image](https://github.com/user-attachments/assets/ca948a6b-6ede-40d5-b522-b18ff284c4ef)

**Comment by uncleflowerpot** [comment]
我也遇到了同样的问题，请问您解决了吗？我移除了其他插件之后还是无法使用。

**Comment by Wang-Zhongwei** [comment]
+1

**Comment by freyaSH** [comment]
I have the same issue, the "Find Available PDF" button isn't available.

**Comment by zhangwanshuai** [comment]
> 我也遇到了同样的问题，请问您解决了吗？我移除了其他插件之后还是无法使用。

没有解决

**Comment by JiaZhang42** [comment]
> 右键没有”查找可用的PDF“ zotero：7.0.1 (64-bit) 插件：1.1.1
> 
> 禁用style插件后没有效果，移除其他插件后也没有效果
> 
> ![image](https://private-user-images.githubusercontent.com/79241424/358964090-2e8746a4-3e46-4d97-99cc-4a4e3f99672c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzgxMTcsIm5iZiI6MTcyNDgzNzgxNywicGF0aCI6Ii83OTI0MTQyNC8zNTg5NjQwOTAtMmU4NzQ2YTQtM2U0Ni00ZDk3LTk5Y2MtNGE0ZTNmOTk2NzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZjkyOTAwYTgzYzRiNWE5ZjU1NDMzYjFmMDA0MDMzMTkxMDRkNzM2OWRlYWU4MTU1MjcwZTMxYzRhNjYxYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jeeF2nJCqny12omS2txKQzhTMuyzT4QzrRRSIN7cdWE) ![image](https://private-user-images.githubusercontent.com/79241424/358963562-ca948a6b-6ede-40d5-b522-b18ff284c4ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzgxMTcsIm5iZiI6MTcyNDgzNzgxNywicGF0aCI6Ii83OTI0MTQyNC8zNTg5NjM1NjItY2E5NDhhNmItNmVkZS00MGQ1LWI1MjItYjE4ZmYyODRjNGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjEyOTc3MjBlYzUwODg4N2I5N2JmNmY4ZDJlZGEyNmMyNTJiOTM4OTFkYWUyNWRhNDY0YTIzMjE0Y2ZhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NduiWi0-SDrVHIkFIUAZPtKLk-hN77sHuyATjCbpaxI)

The button will only appear if no PDF is added or linked to the item. Besides, the button is now named "Find Full Text" in Zotero 7.0.3.

**Comment by freyaSH** [comment]
Hi [JiaZhang42](https://github.com/JiaZhang42)

I see that you are correct, thank you for clarifying. I just got acquainted with the "advanced panel", where the "Find PDF" function is defined as follows: 

<img width="981" alt="Screenshot 2024-08-28 at 12 27 32" src="https://github.com/user-attachments/assets/70aa3410-2eb4-4ec6-bc6a-918fa79eaae6">

I also signed up for a Sem.Sch. API 🗝️, which seemed to have resolved some issues. Not sure if this was necessary, but posting this to help those with the same inquiry that don't speak or write chinese.

**Comment by syt2** [comment]
Items missing a DOI do not have the "Find Full Text" option and cannot be downloaded via Sci-Hub.
Items that already have associated attachments do not have the Find Full Text option.

Add it in [FAQ](https://github.com/syt2/zotero-scipdf?tab=readme-ov-file#faqs) now
