### ISSUE TITLE
右键点击条目后没有“查找可用的 PDF”

### ISSUE THREAD

**Issue by ElayneC** [syt2/zotero-scipdf#19]
如图，在条目右键点击后没有“查找可用的 PDF”选项。
已根据前面的问答尝试将其它插件都移除再单独添加sci-hub插件，还是没有用。
sci-hub的网址是可用的，使用相应的doi号也能在sci-hub上搜到文献。
![屏幕截图 2024-09-15 215749](https://github.com/user-attachments/assets/58b358ce-85bf-4af5-9cdf-627240ebf059)
![屏幕截图 2024-09-15 215643](https://github.com/user-attachments/assets/b2c71cf0-21ce-46de-ba23-256902f0cb27)
![屏幕截图 2024-09-15 215549](https://github.com/user-attachments/assets/ed9c145f-614b-4273-af2c-1ca37e96a81c)
![屏幕截图 2024-09-15 215526](https://github.com/user-attachments/assets/4d53604a-3e12-411b-bee1-16118df56cfd)

**Comment by joeyjoe0111** [comment]
同样的问题+1

**Comment by YirenHuang888** [comment]
同，没有查找可用的pdf选项

**Comment by syt2** [comment]
> 根据zotero的逻辑，如果该条目满足以下任何一个条件，都不会展示查找可用的pdf选项
> 
> 1. 存在pdf或者epub文件
> 2. 不存在doi和url

如 @lzx1026078111 所述
菜单内查找全文选项是否显示 取决于zotero内部的逻辑，与本插件无关

Add it in [FAQ](https://github.com/syt2/zotero-scipdf?tab=readme-ov-file#faqs) now
