### ISSUE TITLE
[Feature Request] Allow Multiple Sci-Hub Mirror Sites

### ISSUE THREAD

**Issue by SeveNOlogy7** [syt2/zotero-scipdf#20]
Would it be possible to add multiple sci-hub mirror sites, that defines multiple PDF resolvers to find pdf in multiple mirrors? 

For example, is it possible to use semicolon separated URL strings in the Scihub URL field: 
`"https://sci-hub.st/{doi}; https://www.sci-hub.ee/{doi};https://sci-hub.ru/{doi};"`

**Comment by syt2** [comment]
added in 1.2.0
