### ISSUE TITLE
[Bug] XPI / Release Folder missing

### ISSUE THREAD

**Issue by mooQ** [syt2/zotero-scipdf#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

XPI / Release Folder missing

**Comment by syt2** [comment]
https://github.com/syt2/zotero-scipdf/releases/download/V1.2.0/sci-pdf.xpi
