### ISSUE TITLE
最新版的zotero7不能使用，找不到设置面板

### ISSUE THREAD

**Issue by pisceswb** [syt2/zotero-scipdf#5]
最新版的zotero7不能使用，找不到设置面板
7.0.0-beta.54+6b996d4f9 (64-bit)

**Comment by pisceswb** [comment]
是安装了其它插件再安装这个不能显示设置面板。把其他的都禁用，先安装这个就可以了

**Comment by pisceswb** [comment]
但条目上右键，没有从sichub下载的选项

**Comment by pisceswb** [comment]
成功显示了一次后，就没有问题了。不能复现找不到设置面板的情况😂

**Comment by pisceswb** [comment]
![image](https://github.com/syt2/zotero-scipdf/assets/104658457/5bd9bbdb-e7f0-4f63-b13b-6753ecf44f01)

**Comment by pisceswb** [comment]
测试了一下，可能是和style插件有点冲突

**Comment by sartre123** [comment]
遇到了同样的问题，不能出现scipdf的插件设置
![Uploading 插件已打开.png…]()

**Comment by sartre123** [comment]
> 最新版的zotero7不能使用，找不到设置面板 7.0.0-beta.54+6b996d4f9 (64-bit)

出现了同样的问题，不能解决。。。插件已打开，但没有插件设置界面，软件版本7.0.0-beta.64+8f8c0d079 (64-bit)

**Comment by sartre123** [comment]
出现了同样的问题，不能解决。。。

**Comment by BlueeHole** [comment]
不好意思，但是请问一下茉莉花插件不是没有适配Zotero 7吗，您是在哪下载的呀

**Comment by sartre123** [comment]
> 不好意思，但是请问一下茉莉花插件不是没有适配Zotero 7吗，您是在哪下载的呀

茉莉花插件在zotero7上可以用，这里讨论的是scipdf插件，利用这个插件可以从scihub上下载论文，十分好用！！！！

**Comment by 17-panyx** [comment]
在zotero7的设置里是能够看到插件的，但是具体条目右键并没有相关查找pdf的选项。是需要将其他插件全部移除先安装这个插件才可以么？

**Comment by pisceswb** [comment]
建议不要使用系统自带的“查找可用PDF”选项，用原来的方式，自己添加一个选项更好用。
当前在zotero7上使用“查找可用PDF”选项，不能使用scihub下载。

**Comment by pisceswb** [comment]
如果通过scihub下载失败，能否进行提示，并告知会通过原下载方式继续下载？
或下载开始时，提示当前会优先通过scihub（附带上在用的scihub网址）下载
@syt2

**Comment by pisceswb** [comment]
或能否增加设置选项：
1. 仅使用scihub下载
2. 仅使用原方式下载
3. 优先使用scihub，失败后使用原方式
4. 优先使用原方式，失败后使用scihub

**Comment by pisceswb** [comment]
下载方式一：文本框可填入 scihub网址1/scihub网址2/原方式/无 等内容
下载方式二：文本框可填入 scihub网址1/scihub网址2/原方式/无 等内容

**Comment by pisceswb** [comment]
因为用系统本身下载总会弹出这个面板，有点烦人。
![image](https://github.com/syt2/zotero-scipdf/assets/104658457/d78c336d-8273-4470-8b5b-47347a9a30e2)

**Comment by Fyangg** [comment]
> 出现了同样的问题，不能解决。。。

你好，请问解决了吗？

**Comment by lyndonlyu** [comment]
同样问题，望修复，设置界面没有设置 build 1.1.1

**Comment by Lee-lai** [comment]
同问题，找不到设置面板，关闭其他插件/重启都不行

**Comment by Lee-lai** [comment]
同问题，找不到设置面板，关闭其他插件/重启都不行
